env:
  browser: true
  es2021: true
  jest: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "react-app"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - "prettier"
rules:
  semi: off
  indent: off
  "react/react-in-jsx-scope": off
  "@typescript-eslint/explicit-module-boundary-types": off
  "react/prop-types": off
